access_password = "holademo"
data_1_url = "https://raw.githubusercontent.com/MikiLeon/mapa_puntos_de_consumo_demo/refs/heads/main/inputs/mapa_consumos_demo.csv"
data_2_url ="https://raw.githubusercontent.com/MikiLeon/mapa_puntos_de_consumo_demo/refs/heads/main/inputs/recursos_drogas.csv"