access_password = "holademo"
data_1_url = "C:\\Users\\miiki\\Desktop\\DATA_SCIENCE\\APRENDIZAJE_PYTHON\\venvs\\mapa_puntos_de_consumo_demo\\inputs\\mapa_consumos_demo.csv"
data_2_url ="C:\\Users\\miiki\\Desktop\\DATA_SCIENCE\\APRENDIZAJE_PYTHON\\venvs\\mapa_puntos_de_consumo_demo\\inputs\\recursos_drogas.csv"